"""add column target_department in table Improvement

Revision ID: c0f674a8ae39
Revises: 
Create Date: 2021-12-07 12:39:58.533126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f674a8ae39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_department', sa.Unicode(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('improvement', schema=None) as batch_op:
        batch_op.drop_column('target_department')

    # ### end Alembic commands ###
